export const headings = [
  { label: "Paragraph", value: 0 },
  { label: "Heading 1", value: 1 },
  { label: "Heading 2", value: 2 },
  { label: "Heading 3", value: 3 },
  { label: "Heading 4", value: 4 },
];

export const fontFamilies = [
  { label: "Arial", value: "Arial", className: "font-[Arial]" },
  {
    label: "Times New Roman",
    value: "Times New Roman",
    className: "font-[Times New Roman]",
  },
  { label: "Verdana", value: "Verdana", className: "font-[Verdana]" },
  {
    label: "Courier New",
    value: "Courier New",
    className: "font-[Courier New]",
  },
  { label: "Georgia", value: "Georgia", className: "font-[Georgia]" },
  { label: "Geist", value: "Geist", className: "font-[Geist]" },
  { label: "Impact", value: "Impact", className: "font-[Impact]" },
  { label: "Roboto", value: "Roboto", className: "font-[Roboto]" },
  { label: "Open Sans", value: "Open Sans", className: "font-[Open Sans]" },
  { label: "Montserrat", value: "Montserrat", className: "font-[Montserrat]" },
  { label: "Lato", value: "Lato", className: "font-[Lato]" },
];

export const fontSizes = [
  { label: "12", value: "12px" },
  { label: "14", value: "14px" },
  { label: "16", value: "16px" },
  { label: "18", value: "18px" },
  { label: "20", value: "20px" },
  { label: "22", value: "22px" },
  { label: "24", value: "24px" },
  { label: "26", value: "26px" },
  { label: "28", value: "28px" },
  { label: "30", value: "30px" },
  { label: "32", value: "32px" },
  { label: "34", value: "34px" },
  { label: "36", value: "36px" },
  { label: "38", value: "38px" },
  { label: "40", value: "40px" },
  { label: "42", value: "42px" },
  { label: "44", value: "44px" },
  { label: "46", value: "46px" },
  { label: "48", value: "48px" },
  { label: "50", value: "50px" },
  { label: "52", value: "52px" },
  { label: "54", value: "54px" },
  { label: "56", value: "56px" },
  { label: "58", value: "58px" },
  { label: "60", value: "60px" },
  { label: "62", value: "62px" },
  { label: "64", value: "64px" },
  { label: "66", value: "66px" },
  { label: "68", value: "68px" },
  { label: "70", value: "70px" },
  { label: "72", value: "72px" },
];

export const lineHeights = [
  { label: "1", value: "1" },
  { label: "1.5", value: "1.5" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
];
